# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=C:\\Program Files\\Java\\jdk-25
#NeoForge ModDev
moddev_version=2.0.141
#Modrinth
modrinth_versions=["26.1","26.1.1","26.1.2"]
#CurseForge
curseforge_id=1080043
#Dependencies
required_dependencies=["neoforge"]
optional_dependencies=[]
#`release`, `beta` or `alpha`
release_channel=alpha
#
# NeoForge Properties
minecraft_version=26.1.1
neoforge_version=26.1.1.14-beta
minecraft_version_range=[26.1,26.1.3)
neoforge_version_range=[26.1,26.1.3)
# Mod Properties
mod_version=26.1.1
maven_group=de.ambertation
archives_base_name=wunderlib
github_base_name=WunderLib
# Dependencies
