# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=C:\\Program Files\\Java\\jdk-25
#Loom
loom_version=1.17.21
#Modrinth
modrinth_versions=["26.3"]
#CurseForge
curseforge_id='1080043'
#Dependencies
required_dependencies=["fabric-api"]
optional_dependencies=[]
#`release`, `beta` or `alpha`
release_channel=release
#
# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=26.3
loader_version=0.19.5
fabric_version=0.161.0+26.3
# Mod Properties
mod_version=26.3.0
maven_group=de.ambertation
archives_base_name=wunderlib
github_base_name=WunderLib
# Dependencies
