# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=C:\\Program Files\\Java\\jdk-25
#NeoForge ModDev
moddev_version=2.0.147
#Modrinth
modrinth_versions=["26.3"]
#CurseForge
curseforge_id=1080043
#Dependencies
required_dependencies=["neoforge"]
optional_dependencies=[]
#`release`, `beta` or `alpha`
release_channel=alpha
#
# NeoForge Properties
minecraft_version=26.3
neoforge_version=26.3.0.7-beta
minecraft_version_range=[26.3,26.4)
neoforge_version_range=[26.3,26.4)
# Mod Properties
mod_version=26.3.0
maven_group=de.ambertation
archives_base_name=wunderlib
github_base_name=WunderLib
# Dependencies
